/* SINCE THE DATA IS COMPLETLY CLEAN AND STANDARDIZED 
WE CAN NOW EXCTRACT SOME INSIGHTS 

-- I - TOTAL FINANCIAL HEALTH TO SEE HOW LUCRATIVE 
THE BUSINESS IS GLOBALLY 

*/

SELECT 
    SUM("Total_Revenue") AS GLOBAL_REVENUE,
    SUM("Total_Cost") AS GLOBAL_COST,
    SUM("Total_Profit") AS GLOBAL_PROFIT,
    ROUND((SUM("Total_Profit") / SUM("Total_Revenue")) * 100, 2) AS PROFIT_MARGIN

FROM 
sales_table;

/*  AFTER RUNNED THE PREVIOUS QUERY YOU CAN NOTICE THAT 
THE NUMBERS APPEARING AS A RESULT ARE NOT PROPERLY READ
SO WE ARE GOING TO IMPROVE A BIT READABILITY BY ADDING
1- DOLLARS SIGN
2- COMMAS 
USE TO_CHAR (SUM(" COLUMN "), '$99,999,999,999,99'AS ..... FR
FORMATING
*/

SELECT 
    TO_CHAR(SUM("Total_Revenue"), '$99,999,999,999,99') AS GLOBAL_REVENUE,
    TO_CHAR(SUM("Total_Cost"), '$99,999,999,999,99') AS GLOBAL_COST,
    TO_CHAR(SUM("Total_Profit"), '$99,999,999,999,99') AS GLOBAL_PROFIT,
    ROUND((SUM("Total_Profit") / SUM("Total_Revenue")) * 100, 2) AS PROFIT_MARGIN

FROM 
sales_table; 