/* III -  CHECKING PERFORMANCE BY REGION :
--> WHAT REGION HAS THE HIGHEST PRPFIT MARGIN, AND 
WHAT REGION HAS THE HIGHEST REVENUE BUT LOW PROFIT 
MARCHINS MARGINS ?
*/

SELECT 
    sales_table."Region",
    TO_CHAR(SUM("Total_Profit"), '$99,999,999,999,99') AS Total_Profit,
    ROUND((SUM("Total_Profit") / SUM("Total_Revenue")) * 100, 2) AS PROFIT_MARGIN
FROM sales_table
GROUP BY sales_table."Region"
ORDER BY PROFIT_MARGIN DESC;